version: '3.7'
services:
  reverse:
      image: nginx
      container_name: reverse-proxy
      hostname: proxy
      ports:
        - 9000:80
      volumes:
        - ./config:/etc/nginx
        - ./html:/usr/share/nginx/html